# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DENO_KEY : ${{ secrets.DENO_KEY  }}
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read
    steps:
      - name: test
        run: echo $DENO_KEY
        
      - name: Clone repository
        uses: actions/checkout@v3
        
      - name: deno setup
        uses: denoland/setup-deno@v1
        with:
            deno-version: v1.x
      
      - name : build mdx
        run : deno run -A --unstable build.ts

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: blog1444 # the name of the project on Deno Deploy
          entrypoint: main.ts # the entrypoint to deploy
          import-map: import_map.json
